# Generated by Django 3.2.3 on 2021-06-08 09:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import fulfillment_service.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', fulfillment_service.utils.fields.PositiveBigDecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('overall_sum', fulfillment_service.utils.fields.PositiveBigDecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='The purchased sum of the specific asset')),
                ('asset_name', models.CharField(max_length=20, verbose_name='The short name of an asset that represents it on a market, e.g. GOOG')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_of_return', fulfillment_service.utils.fields.BigDecimalField(decimal_places=2, max_digits=17)),
                ('volatility', fulfillment_service.utils.fields.PositiveBigDecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('value_at_risk', fulfillment_service.utils.fields.BigDecimalField(decimal_places=2, max_digits=17)),
            ],
        ),
    ]
