# Generated by Django 3.2.3 on 2021-06-07 13:20

from django.db import migrations
from fulfillment_service.utils.migrations import load_statements


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            load_statements('users/sql/users.sql'),
            load_statements('users/sql/drop_users.sql'),
        ),
    ]
