exclude: 'docs|node_modules|migrations|.git|.tox'
files: ui-fulfillment/
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args: ['--config=backend/ui-fulfillment/pyproject.toml']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ['--settings-file=backend/ui-fulfillment/pyproject.toml']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=backend/ui-fulfillment/setup.cfg']
        additional_dependencies: [flake8-isort]
