[tool.black]
skip-string-normalization = true
target-version = ['py39']
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "--ds=config.settings.local --reuse-db"
python_files = ["tests.py", "test_*.py"]

[tool.coverage.run]
include = ["fulfillment_service/*"]
omit = ["*migrations*", "*tests*"]
plugins = ["django_coverage_plugin"]
